
-- 1. Tabla de CLIENTES
-- Información básica y de contacto
create table public.clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  first_name text not null,
  last_name text not null,
  email text,
  phone text,
  birth_date date,
  start_date date default current_date,
  status text default 'active' check (status in ('active', 'inactive', 'paused')),
  emergency_contact text,
  avatar_url text
);

-- 2. Tabla de EJERCICIOS (Catálogo)
-- Lista de ejercicios disponibles para asignar
create table public.exercises (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  muscle_group text, -- ej: Pecho, Espalda, Piernas
  category text, -- ej: Fuerza, Cardio, Movilidad
  video_url text
);

-- 3. Tabla de HISTORIAL CLÍNICO / ANAMNESIS
-- Información médica relevante, lesiones previas, objetivos
create table public.medical_records (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id bigint references public.clients(id) on delete cascade not null,
  condition text not null, -- Título de la condición o lesión
  description text, -- Detalles
  date_recorded date default current_date,
  status text default 'active' check (status in ('active', 'resolved', 'chronic'))
);

-- 4. Tabla de REGISTROS DE ENTRENAMIENTO (Workout Logs)
-- Historial de lo que ha hecho el cliente: pesos, series, etc.
create table public.workout_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id bigint references public.clients(id) on delete cascade not null,
  exercise_id bigint references public.exercises(id) on delete set null,
  date timestamp with time zone default timezone('utc'::text, now()) not null,
  weight_kg numeric,
  sets integer,
  reps integer,
  rpe integer, -- Percepción de esfuerzo (1-10)
  notes text -- Notas específicas de ese ejercicio ese día
);

-- 5. Tabla de NOTAS DE SEGUIMIENTO
-- Bitácora general: "Hoy vino desmotivado", "Mejoró técnica", etc.
create table public.client_notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_id bigint references public.clients(id) on delete cascade not null,
  content text not null,
  type text default 'general' -- general, nutricion, administrativo
);

-- SEGURIDAD (Row Level Security)
-- Habilitar seguridad para que solo usuarios autenticados (tú) puedan ver/editar

-- Habilitar RLS
alter table public.clients enable row level security;
alter table public.exercises enable row level security;
alter table public.medical_records enable row level security;
alter table public.workout_logs enable row level security;
alter table public.client_notes enable row level security;

-- Políticas de acceso total para usuarios autenticados (Admin)
create policy "Acceso total a clientes para autenticados" on public.clients
  for all to authenticated using (true);

create policy "Acceso total a ejercicios para autenticados" on public.exercises
  for all to authenticated using (true);

create policy "Acceso total a historial médico para autenticados" on public.medical_records
  for all to authenticated using (true);

create policy "Acceso total a logs para autenticados" on public.workout_logs
  for all to authenticated using (true);

create policy "Acceso total a notas para autenticados" on public.client_notes
  for all to authenticated using (true);

-- DATOS DE EJEMPLO (Opcional: Ejecutar para tener datos iniciales)
insert into public.exercises (name, muscle_group, category) values 
('Sentadilla (Squat)', 'Piernas', 'Fuerza'),
('Peso Muerto (Deadlift)', 'Espalda/Piernas', 'Fuerza'),
('Press de Banca', 'Pecho', 'Fuerza'),
('Dominadas', 'Espalda', 'Fuerza');

insert into public.clients (first_name, last_name, email, status) values 
('Juan', 'Pérez', 'juan@example.com', 'active'),
('Ana', 'García', 'ana@example.com', 'active');
